language: ruby
rvm:
  - 2.3.1
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec
  - bundle exec rubocop --config .rubocop.yml app/models/ app/controllers/ app/helpers/ config/initializers/ spec/
services:
  - postgresql
