language: ruby
rvm:
  - 2.3.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec
  - bundle exec rubocop --config .rubocop.yml app/models/ app/controllers/ app/helpers/ spec/
services:
  - postgresql
